// <auto-generated />
using System;
using Amphawan_001.Dbcontext_model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Amphawan_001.Migrations
{
    [DbContext(typeof(CL_dbContext))]
    partial class CL_dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Amphawan_001.Models.MD_Account", b =>
                {
                    b.Property<int>("int_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date_login_user")
                        .HasColumnType("datetime2");

                    b.Property<bool>("bool_staus")
                        .HasColumnType("bit");

                    b.Property<bool>("bool_stop_")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dt_cus_begin_cus_day")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dt_cus_birth_day")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dt_cus_expire_cus_day")
                        .HasColumnType("datetime2");

                    b.Property<int>("int_type_cus")
                        .HasColumnType("int");

                    b.Property<string>("st_Email_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("st_compare_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("st_cus_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("st_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("st_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("st_post_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("st_user")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("int_id");

                    b.ToTable("tb_account");
                });

            modelBuilder.Entity("Amphawan_001.Models.MD_catralog_book", b =>
                {
                    b.Property<int>("int_id_catalog_book")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("MD_Accountint_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("dt_DATE_modify")
                        .HasColumnType("datetime2");

                    b.Property<string>("st_ISBN_ISSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("st_detail_book")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("st_name_book")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("int_id_catalog_book");

                    b.HasIndex("MD_Accountint_id");

                    b.ToTable("tb_cattalog");
                });

            modelBuilder.Entity("Amphawan_001.Models.MD_customer", b =>
                {
                    b.Property<int>("int_id_cus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("st_cus_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("int_id_cus");

                    b.ToTable("tb_customer");
                });

            modelBuilder.Entity("Amphawan_001.Models.MD_history", b =>
                {
                    b.Property<int>("int_id_his")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("int_id_his");

                    b.ToTable("tb_his");
                });

            modelBuilder.Entity("Amphawan_001.Models.MD_search", b =>
                {
                    b.Property<int>("int_id_num")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("int_kind_book")
                        .HasColumnType("int");

                    b.Property<int>("int_order_by")
                        .HasColumnType("int");

                    b.Property<int>("int_type_book")
                        .HasColumnType("int");

                    b.Property<string>("st_keyword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("int_id_num");

                    b.ToTable("tb_search");
                });

            modelBuilder.Entity("Amphawan_001.Models.MD_catralog_book", b =>
                {
                    b.HasOne("Amphawan_001.Models.MD_Account", null)
                        .WithMany("Fk_Catralog_s")
                        .HasForeignKey("MD_Accountint_id");
                });

            modelBuilder.Entity("Amphawan_001.Models.MD_Account", b =>
                {
                    b.Navigation("Fk_Catralog_s");
                });
#pragma warning restore 612, 618
        }
    }
}
